export enum ServiceName {
    USER_SERVICE = 'USER_SERVICE',
    NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
    AUTHENTICATION_SERVICE = 'AUTHENTICATION_SERVICE',
    VENDOR_SERVICE = 'VENDOR_SERVICE',
}